### ISSUE TITLE
No "Incoming Web Hooks"

### ISSUE THREAD

**Issue by M1kep** [mhouston100/PSMicrosoftTeams#1]
Hello there,

I'm looking to get this setup. I've created the channel and selected the connector but incoming webhooks is not showing. It seems this may be a setting on the admin portal. Also, it seems some people are unable to enable them.

https://techcommunity.microsoft.com/t5/Microsoft-Teams/Incoming-Webhook-This-card-action-is-disabled/td-p/52867

**Comment by mhouston100** [comment]
Are you creating it through the 'Teams' app or through the WebApp?

I've just created a test channel through the WebApp and was able to create a WebHook with no issues.

So in the 'Connector' popup if you sort by 'Popularity' it's the third one down for me.

![image](https://user-images.githubusercontent.com/4596455/35469866-9b3b50ea-0392-11e8-97ae-6f80d52be997.png)


The issue you linked to is about the 'Action' buttons INSIDE the cards not working, not the creating of a WebHook or sending of notifications.

**Comment by M1kep** [comment]
Interesting you have WAY more options. I'll sit down with one of our admins on Monday to take a look! Thank you

![image](https://user-images.githubusercontent.com/2661819/35470798-ec02ce2e-0304-11e8-9ca9-f8f4d6449444.png)

**Comment by mhouston100** [comment]
That is very strange, the Web Connector is free too so I doubt it is related to licensing.

I'm going to close this off as it's not an issue related to the module itself though!
