### ISSUE TITLE
Sccm Example

### ISSUE THREAD

**Issue by CMDRPhaedra** [mhouston100/PSMicrosoftTeams#5]
What do you mean when you say "By default the script requires the local disk have a partition, if you have it at a stage where the disk is blank, make sure you adjust your SCCM settings to reflect this"

**Comment by mhouston100** [comment]
It may not be required any more, previously the module wrote a log to the drive which would fail if the drive was not formatted yet.

For instance, if you put this as the first step in your HDD but the drive was blank, it would fail the TS as there was nowhere to write the log to.
