### ISSUE TITLE
Not an issue but rather question - get-controlledGPO

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mhouston100/PSMicrosoftTeams#6]
Hi,

as in topic... I'm interested in get-controlledGPO which is in examples.... is this something private or even pay product? Or did you actually manage to get all data from AD Events? I'm playing with GPO's for my PSWinReporting (https://github.com/EvotecIT/PSWinReporting) product but the way I see it its extremely hard to fully extract GPO information, especially for the deleted GPO's. 

With regards,
Przemek

**Comment by mhouston100** [comment]
Sorry, I missed this. Get-ControlledGPO is a module that comes with AGPM (Advanced Group Policy Management) which is Microsofts version control system for GPO. It comes free with Volume Licensing as part of the Dektop Optimization Pack and I would highly recommend it!

Does things like granular GPO security, tracking and logging, approval workflow, history and versioning comparing etc. 

https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/agpm/

**Comment by mhouston100** [comment]
I'll close this off now!

**Comment by PrzemyslawKlys** [comment]
Thanks :-) Was wondering if you made it yourself.
