### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException

### ISSUE THREAD

**Issue by Tony-A-Michailidis** [mhouston100/PSMicrosoftTeams#8]
I am getting, just started yesterday: "Send-TeamsMessage - Execute System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information." Any idea what has changed? Thanks.

**Comment by adutra22** [comment]
I'm receiving the same error as well. Seemed to work fine on Friday when I first implemented Teams Webhooks, but came in to work today and got this error.

**Comment by TonyMichailidisDFO** [comment]
I was replying to the other e-mail about the critical issue logged, should I continue?

**Comment by Tony-A-Michailidis** [comment]
I opened a ticket with azure support, lets see.

**Comment by mhouston100** [comment]
Was a long weekend here in Sydney, just getting to this now.

I have not experienced this at all in our environment, our notifications continued to come through over the weekend.

Is there anything specific regarding your environment that might be affecting it?

**Comment by Tony-A-Michailidis** [comment]
Nothing I can think of has changed. Actually it stopped working while I was testing a new runbook that is using it. Perhaps it is Teams related and data center specific? I assume by Sydney you mean down under? We are up north (waaay north lol). Will monitor it and see what comes up. Do you by any chance know anyone else in North America who is using this project or directly calling "Invoke-RestMethod -uri <some incoming webhook> -Method Post -body $body -ContentType 'application/json' ? Cheers - Tony.

**Comment by ghost** [comment]
Same problem here in The Netherlands currently. Looks like a rolling update of some kind which is causing this issue.

**Comment by Tony-A-Michailidis** [comment]
It appears to be working today, All: try again. Thanks - Tony.

**Comment by ghost** [comment]
Not yet working for me here in the Netherlands, but I'll give it some time.

**Comment by adutra22** [comment]
Not yet working here in California either. And its not just this code, its something on Teams side. I wrote a very simple webhook for teams that was working Friday, and it stopped working as well.

**Comment by ghost** [comment]
It appears to be working again today in The Netherlands, so seems to have been a global issue.

**Comment by adutra22** [comment]
Started working again last night in California.

**Comment by mhouston100** [comment]
I'm going to close this off as it was service related
